/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.util.Config;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(Config.get("db.url"));
    }
}
